version: '3'
services:
  vsftpd:
    build: .
    image:yi/ftp:0.0
    ports:
        - "20-21:20-21"
        - "65500-65515:65500-65515"
    container_name: vsftpd
    volumes:
        - "/media/common/DOCKER_IMAGES/Tensorflow:/var/ftp:ro"
