#!/bin/bash

set -e

ANON_ROOT=${ANON_ROOT:-/var/ftp}
MAX_PORT=${MAX_PORT:-65515}
MIN_PORT=${MIN_PORT:-65500}
MAX_PER_IP=${MAX_PER_IP:-2}
MAX_LOGIN_FAILS=${MAX_LOGIN_FAILS:-2}
MAX_CLIENTS=${MAX_CLIENTS:-50}
MAX_RATE=${MAX_RATE:-0}
FTPD_BANNER=${FTPD_BANNER:-"Welcome To YI Public FTP Server"}


[ -f /etc/vsftpd.conf ] || cat <<EOF > /etc/vsftpd.conf
listen=YES
# Allow anonymous FTP? (Disabled by default).
anonymous_enable=YES
# Stop prompting for a password on the command line
no_anon_password=YES
#Show the user and group as ftp:ftp, regardless of the owner
hide_ids=YES
dirmessage_enable=YES
use_localtime=YES
connect_from_port_20=YES
write_enable=NO
seccomp_sandbox=NO
xferlog_std_format=NO
log_ftp_protocol=YES
#Point anonymous user to the ftp root directory
anon_root=${ANON_ROOT}
# Limit the range of ports that can be used for passive FTP
pasv_max_port=${MAX_PORT}
pasv_min_port=${MIN_PORT}
max_per_ip=${MAX_PER_IP}
max_login_fails=${MAX_LOGIN_FAILS}
max_clients=${MAX_CLIENTS}
anon_max_rate=${MAX_RATE}
ftpd_banner=${FTPD_BANNER}
EOF

# Remove any trailing space and CR characters from /etc/vsftpd.conf
sed -i 's,\r,,;s, *$,,' /etc/vsftpd.conf

/usr/sbin/vsftpd "$@"
